import Head from 'next/head'
import styles from '@/styles/Post.module.scss'
import Layout from '@/components/layout/layout'
import type { GetServerSideProps } from 'next'

type TPost = {
  userId: number
  id: number
  title: string
  body: string
}

type TProps = {
  post: TPost
  email: string
}

export default function ({ post, email }: TProps) {
  return (
    <>
      <Head>
        <title>Posts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Layout>
        <div className={styles.post}>
          <h1 className={styles.title}>{post.title}</h1>
          <div className={styles.text}>{post.body}</div>
          <a href={`mailto:${email}`}>{email}</a>
        </div>
      </Layout>
    </>
  )
}

export const getServerSideProps = (async context => {
  const id = context.query.id
  const resPost = await fetch(
    `https://jsonplaceholder.typicode.com/posts/${id}`
  )
  const post: TPost = await resPost.json()
  const resUser = await fetch(
    `https://jsonplaceholder.typicode.com/users/${post.userId}`
  )
  const user = await resUser.json()
  return { props: { post, email: user.email } }
}) satisfies GetServerSideProps<{ post: TPost }>
